services:

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: openhalo
      MYSQL_USER: halo
      MYSQL_PASSWORD: halopass
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: openhalo
      POSTGRES_USER: halo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  openhalo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openhalo
    restart: unless-stopped
    environment:
      HALO_HOME: /opt/openhalo/1.0
      PGHOST: postgres
      PGUSER: halo
      PGPASSWORD: mysecret
      MYSQL_HOST: mysqldb
      MYSQL_USER: halo
      MYSQL_PASSWORD: halopass
    depends_on:
      - mysqldb
      - postgres
    ports:
      - "3308:3308"
      - "5434:5434"
    volumes:
      - openhalo_data:/home/halo/ohdata
      - pathtofile/name_basics_mysql.sql:/home/halo/name_basics_mysql.sql:ro

volumes:
  mysqldb_data:
  pg_data:
  openhalo_data:
